### ISSUE TITLE
嗨，我遇到了点问题

### ISSUE THREAD

**Issue by AdminQQZ** [hsl5430/BadgeTabLayout#2]
![image](https://user-images.githubusercontent.com/12959954/71989229-3aa57480-326c-11ea-95c1-6f35a1f6edd6.png)

**Comment by AdminQQZ** [comment]
![image](https://user-images.githubusercontent.com/12959954/72030610-83891780-32c4-11ea-8f83-d9e5ce3485f5.png)
我做了一个判断。不知道会不会有影响。

**Comment by AdminQQZ** [comment]
断点进去了，发现设置了setText()。但是都不显示红点哎
![image](https://user-images.githubusercontent.com/12959954/72031550-a5d06480-32c7-11ea-980d-ba8138081fd2.png)

**Comment by AdminQQZ** [comment]
![image](https://user-images.githubusercontent.com/12959954/72032091-6145c880-32c9-11ea-86bb-1057d4e2d37a.png)
 嗨，小红点，通过  app:badge_background="@drawable/shape_bg_badge" 设置显示出来了，但是，无法设置数字

**Comment by HSL5430** [comment]
1. 图一：NullPointerException应该是因为你未给BadgeTabView布局设置**style="@style/BadgeTabView"**(推荐)
或者你需要指定属性app:badge_background;
2. 图二：应该是你加的一个判断导致的，解决方案同上
3. 图三：showBadge(int number)后你是否又调用了showBadge()，或者检查下有无设置badge相关属性：badge_textColor、badge_textSize，建议直接使用style（同上）
